# Generated by Django 4.1.1 on 2022-10-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_familia_delete_personas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
